### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'log_dir'

### ISSUE THREAD

**Issue by zjplab** [khanrc/pt.darts#13]
Running the code on Google Colab, I got:
```
Traceback (most recent call last):
  File "search.py", line 19, in <module>
    writer = SummaryWriter(log_dir=os.path.join(config.path, "tb"))
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/writer.py", line 254, in __init__
    self._get_file_writer()
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/writer.py", line 310, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.logdir, **self.kwargs)
TypeError: __init__() got an unexpected keyword argument 'log_dir'
```

**Comment by jafermarq** [comment]
Hi. Probably you are using a different version of TensorBoardX. You can solve this error by updating line 19 of `search.py` by defining the input argument as `logdir` instead of `log_dir`.
