### ISSUE TITLE
batch_size issue

### ISSUE THREAD

**Issue by buttercutter** [khanrc/pt.darts#40]
I ran `python search.py --name cifar10 --dataset cifar10 --batch_size 32` , but I have the following error at [utils.py](https://github.com/khanrc/pt.darts/blob/master/utils.py#L103). Why ?

```
Traceback (most recent call last):
  File "/home/phung/Downloads/darts/pt.darts/search.py", line 201, in <module>
    main()
  File "/home/phung/Downloads/darts/pt.darts/search.py", line 84, in main
    train(train_loader, valid_loader, model, architect, w_optim, alpha_optim, lr, epoch)
  File "/home/phung/Downloads/darts/pt.darts/search.py", line 144, in train
    prec1, prec5 = utils.accuracy(logits, trn_y, topk=(1, 5))
  File "/home/phung/Downloads/darts/pt.darts/utils.py", line 103, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

**Comment by buttercutter** [comment]
Problem solved using https://github.com/promach/pt.darts/

**Comment by skbhat** [comment]
First apply .contiguous() before view.  Eg: 

correct_k = correct[:k].view(-1).float().sum(0)  must be changed to correct_k = correct[:k].contiguous().view(-1).float().sum(0)

Suggested by https://github.com/cezannec/capsule_net_pytorch/issues/4
